name: Publish snapshot package to the Maven Central Repository
on:
  push:
    branches:
    - 'master'
    - 'candidate-*'
  create:
    branches:
    - 'candidate-*'

jobs:
  publish-maven-central:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        if: contains(github.ref_name, '-release') == false
        run: mvn --batch-mode -DskipITs deploy
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_USER_NAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_PASS }}
  publish-jfrog-artifactory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Jfrog Artifactory Deployment
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: 'jfrog-snapshot'
          server-username: JFROG_USER
          server-password: JFROG_TOKEN
          gpg-private-key: ${{ secrets.CENTRAL_SIGNING_SECRET }}
          gpg-passphrase: JFROG_GPG_PASSPHRASE
      - name: Publish package
        if: contains(github.ref_name, '-release') == false
        run: mvn -Pjfrog-artifactory -Dgpg.passphrase=${{ secrets.CENTRAL_SIGN_MODULES_PASSPHRASE }} -DstagingProgressTimeoutMinutes=20 -DskipITs clean deploy -e
        env:
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
          JFROG_GPG_PASSPHRASE: ${{ secrets.SIGN_MODULES_PASSPHRASE }}
          JFROG_URL: ${{ vars.JFROG_URL }}
          JFROG_SNAPSHOT_REPOSITORY: ${{ vars.JFROG_SNAPSHOT_REPOSITORY }}
          JFROG_REPOSITORY: ${{ vars.JFROG_REPOSITORY }}
